---
services:
  db:
    container_name: powerpass_db
    restart: unless-stopped
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: powerpass
      POSTGRES_PASSWORD: powerpass
      POSTGRES_DB: powerpass
    volumes:
      - powerpass_db:/var/lib/postgresql/data

  backend:
    container_name: powerpass_backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://powerpass:powerpass@powerpass_db:5432/powerpass
    ports:
      - "8000:8000"

  frontend:
    container_name: powerpass_frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000 # Fix here your API URL
    ports:
      - "3000:80"

volumes:
  powerpass_db:
...
