FROM python:3.13.3-alpine3.22

WORKDIR /workspace/backend

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt \
    && apk add --no-cache git=2.49.0-r0

CMD ["fastapi", "dev", "app/main.py", "--port", "8000", "--host", "0.0.0.0"]