---
services:
  db:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: powerpass
      POSTGRES_PASSWORD: powerpass
      POSTGRES_DB: powerpass
    volumes:
      - powerpass_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://powerpass:powerpass@db:5432/powerpass
    volumes:
      - ../:/workspace
    working_dir: /workspace/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/workspace
    working_dir: /workspace/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  powerpass_db:
...